version: "3.2"

services:
  dev:
    container_name: e2-chain
    image: paritytech/ci-linux:production
    working_dir: /var/www/e2-chain
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/e2-chain/.cargo
    volumes:
      - .:/var/www/e2-chain
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/e2-chain --dev --ws-external"
